param(
  [string]$RepoRoot = ""
)

$ErrorActionPreference = "Stop"

. "$PSScriptRoot\lib\dotenv.ps1"
. "$PSScriptRoot\lib\steam.ps1"
. "$PSScriptRoot\lib\godot.ps1"
. "$PSScriptRoot\lib\vscode.ps1"

function Get-RepoRoot {
  if ($RepoRoot) { return $RepoRoot }
  return (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

function Escape-Xml([string]$Value) {
  return $Value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;")
}

function Build-PropLine([string]$Name, [string]$Value) {
  if (-not $Value) { return "" }
  return "    <$Name>$(Escape-Xml $Value)</$Name>`r`n"
}

$root = Get-RepoRoot
$localPropsPath = Join-Path $root "local.props"

Import-DotEnv -Path (Join-Path $root ".env")

$sts2Dir = Resolve-Sts2Dir
if (-not $sts2Dir) {
  throw "Slay the Spire 2 not found. Set STS2_DIR in .env."
}
if (-not (Test-Path $sts2Dir)) {
  throw ("STS2 directory not found: " + $sts2Dir)
}

$godotPath = Resolve-GodotPath
if (-not $godotPath) {
  Write-Warning "MegaDot/Godot not found. 'make pck' will not work. Set GODOT_PATH in .env."
}

$props  = Build-PropLine "Sts2Dir"   $sts2Dir
$props += Build-PropLine "GodotPath" $godotPath

$localPropsContent = @"
<!-- Generated by make init - do not commit -->
<Project>
  <PropertyGroup>
$props  </PropertyGroup>
</Project>
"@

Set-Content -Path $localPropsPath -Encoding UTF8 -Value $localPropsContent.Trim()

Write-Host ("Generated " + $localPropsPath)
Write-Host ("  Sts2Dir   = " + $sts2Dir)
if ($godotPath) { Write-Host ("  GodotPath = " + $godotPath) }

Setup-DebugLaunch -Sts2Dir $sts2Dir
Write-VSCodeFiles -Root $root -Sts2Dir $sts2Dir

Write-Host ""
Write-Host "Done. You can now run:"
Write-Host "  make compile     -- dotnet build: DLL/manifest to game mods (no .pck)"
Write-Host "  make pck         -- dotnet publish + Godot .pck to game mods"
Write-Host "  make sync        -- build + deploy into game mods"
Write-Host "  make deploy      -- only deploy from build/DevMode/ (after make build)"
Write-Host "  make build       -- artifacts under build/DevMode/ only (no game copy)"
